In [1]:
#distance square
def dist_sq(a, b):
    return np.sum((a-b)**2)
#distance square for every point to the centroid
def point_sq(data,index):
    Dist=list()
    for i in range(data.shape[0]):
        Dist.append(dist_sq(data.ix[index],data.ix[i]))
    return Dist
def dist_prob(Dist):
    return (Dist/np.sum(np.array(Dist)))

In [2]:
def kmeansplusplus(data, k, d):
    centroid=np.zeros([k,d])
    index=np.random.choice(data.shape[0],1)
    centroid[0]=data.ix[index]
    for number in range(k-1):
        distance=point_sq(data,index)
        prob=dist_prob(distance).tolist()
        #prob[index]=0
        index=np.random.choice(data.shape[0],1,prob)
        centroid[number+1]=data.ix[index]
    return centroid


In [16]:
#test 
data=DataFrame([np.random.random(100),np.random.random(100)]).transpose()
initial= kmeansplusplus(data,8,2)

In [4]:
initial

array([[ 0.65077554,  0.45060154],
       [ 0.51919039,  0.4426771 ],
       [ 0.44355613,  0.73092667],
       [ 0.95592707,  0.01548187],
       [ 0.16051251,  0.59400177],
       [ 0.79010187,  0.09990044],
       [ 0.51654993,  0.31330496],
       [ 0.1453507 ,  0.42704333]])

In [32]:
initial.all==getCentroids(data,l).all

False

In [6]:
shouldStop(initial, getCentroids(data,l), 3)

NameError: name 'shouldStop' is not defined

In [34]:
def kmeans(dataSet, initial):
    centroids=initial
    # Initialize book keeping vars.
    iterations = 0
    oldCentroids = None
    
    # Run the main k-means algorithm
    while not shouldStop(oldCentroids, centroids, iterations):
        # Save old centroids for convergence test. Book keeping.
        oldCentroids = centroids
        iterations += 1
        
        # Assign labels to each datapoint based on centroids
        l= getLabels(dataSet, centroids)
        
        # Assign centroids based on datapoint labels
        centroids = getCentroids(dataSet, l)
        
    # We can get the labels too by calling getLabels(dataSet, centroids)
    return centroids, l


In [33]:
# Function: Should Stop
# -------------
# Returns True or False if k-means is done. K-means terminates either
# because it has run a maximum number of iterations OR the centroids
# stop changing.
def shouldStop(oldCentroids, centroids, iterations):
    if iterations > 10: return True
    return oldCentroids.all == centroids.all


In [25]:
# Function: Get Labels
# -------------
# Returns a label for each piece of data in the dataset. 
def getLabels(dataSet, centroids):
    # For each element in the dataset, chose the closest centroid. 
    # Make that centroid the element's label.
    l=[]
    for i in range(dataSet.shape[0]):
        dist=np.zeros(centroids.shape[0])
        for j in range(centroids.shape[0]):
            dist[j]=dist_sq(dataSet.ix[i],centroids[j])
        l.append(np.argmin(dist))
    return l
            


In [15]:
# Function: Get Centroids
# -------------
# Returns k random centroids, each of dimension n.
def getCentroids(dataSet, labels):
    # Each centroid is the geometric mean of the points that
    # have that centroid's label. Important: If a centroid is empty (no points have
    # that centroid's label) you should randomly re-initialize it.
    data_new = dataSet.copy()
    data_new['Labels'] = labels
    data_new = data_new.groupby(['Labels']).mean().iloc[:,:2]
    return np.array(data_new)
    

In [19]:
l=getLabels(data, initial)


In [12]:
getCentroids(data,l)

array([[ 0.79763431,  0.59417898],
       [ 0.50396127,  0.44920215],
       [ 0.52852529,  0.83247211],
       [ 0.94573081,  0.10057897],
       [ 0.15603868,  0.69250183],
       [ 0.696148  ,  0.13246915],
       [ 0.44526922,  0.21054137],
       [ 0.10320822,  0.29491949]])

In [20]:
data

0         1
0   0.430954  0.371030
1   0.867310  0.026146
2   0.096540  0.529266
3   0.207957  0.652664
4   0.734970  0.177697
5   0.322341  0.303808
6   0.564856  0.682017
7   0.593204  0.918000
8   0.207437  0.392279
9   0.025163  0.338477
10  0.164676  0.338466
11  0.381006  0.727928
12  0.619534  0.067942
13  0.800053  0.350509
14  0.834444  0.660203
15  0.056435  0.052818
16  0.604612  0.969696
17  0.700368  0.383279
18  0.501493  0.037943
19  0.705115  0.728953
20  0.943546  0.886176
21  0.779189  0.632537
22  0.022427  0.240478
23  0.925653  0.182844
24  0.056774  0.696798
25  0.483489  0.867841
26  0.509906  0.146505
27  0.262468  0.230827
28  0.563503  0.378873
29  0.723238  0.626199
..       ...       ...
70  0.838275  0.993392
71  0.153601  0.595566
72  0.424617  0.009945
73  0.229424  0.991443
74  0.495697  0.493906
75  0.633066  0.790066
76  0.039283  0.074260
77  0.370612  0.334279
78  0.256733  0.621179
79  0.544801  0.544459
80  0.414298  0.668008
81  0.275657  0.968951
82  0.050219  0.878427
83  0.881209  0.002647
84  0.834708  0.500477
85  0.283771  0.957219
86  0.315753  0.929723
87  0.231967  0.922647
88  0.099005  0.363076
89  0.746724  0.991606
90  0.758740  0.718543
91  0.131862  0.551730
92  0.916798  0.346889
93  0.524815  0.820807
94  0.539063  0.413079
95  0.368835  0.033550
96  0.694515  0.377618
97  0.593711  0.507054
98  0.730395  0.917851
99  0.454898  0.634024

[100 rows x 2 columns]

In [35]:
kmeans(data, initial)

AttributeError: 'NoneType' object has no attribute 'all'

In [301]:
Dist=np.zeros(100)
for i in range(data.shape[0]):
    Dist[i]=dist_sq(data.ix[70],data.ix[i])
Dist

array([ 0.17403111,  0.06167224,  0.39671919,  0.3216551 ,  0.36006365,
        0.11823907,  0.51882048,  0.62793715,  0.41837158,  0.16604132,
        0.32680451,  0.69359363,  0.61359448,  0.07338759,  0.14862169,
        0.19261274,  0.1417082 ,  0.07470282,  0.01614999,  0.0197996 ,
        0.29719696,  0.05152942,  0.03124162,  0.18358687,  0.08624386,
        0.02988028,  0.39083512,  0.41853587,  0.21024576,  0.02746001,
        0.60831221,  0.1859697 ,  0.00393843,  0.24080248,  0.54791644,
        0.07136598,  0.09875725,  0.12325046,  0.07583565,  0.05133039,
        0.10668365,  0.11676853,  0.39460411,  0.23895327,  0.02028611,
        0.11168459,  0.10583707,  0.19483812,  0.00607086,  0.48149276,
        0.10705208,  0.15629711,  0.0805121 ,  0.09103883,  0.09299861,
        0.09137751,  0.09877783,  0.46822743,  0.47514698,  0.27089297,
        0.3558764 ,  0.26529638,  0.11231946,  0.22046877,  0.06158305,
        0.10773211,  0.18432143,  0.15064605,  0.61810243,  0.25

In [476]:
initial.shape[0]

8

In [312]:
sq=np.array(sq)

array([ 0.07838389,  0.05716342,  0.63979241,  0.01056759,  0.        ,
        0.02600466,  0.02312395,  0.42996646,  0.14347695,  0.3580453 ,
        0.42609344,  0.15531775,  0.18019009,  0.43690041,  0.35092232,
        0.65572659,  0.51234454,  0.03716512,  0.40468589,  0.13408083,
        0.67470531,  0.0038319 ,  0.03238977,  0.22870282,  0.32016634,
        0.35465964,  0.53606707,  0.06592874,  0.12844287,  0.76345253,
        0.07948402,  0.3505201 ,  0.07149165,  0.19187074,  0.58118992,
        0.08136736,  0.21590403,  0.34788092,  0.09993989,  0.11410655,
        0.53972394,  0.11768722,  0.23369232,  0.24240948,  0.04477737,
        0.15503012,  0.0931706 ,  0.0363362 ,  0.01640115,  0.11949338,
        0.32035971,  0.08347794,  0.0932965 ,  0.02961029,  0.77666678,
        0.40513639,  0.08745263,  0.10833973,  0.11621421,  0.62791042,
        0.21276357,  0.34428002,  0.78795535,  0.61856352,  0.34855379,
        0.45002158,  0.6148304 ,  0.06349472,  0.51613392,  0.47

In [321]:
np.argmin(sq)

4

In [324]:
data.shape[0]

100